language: php

php:
  - 7.1

matrix:
  include:
    - php: 7.1
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - bash <(curl -s https://codecov.io/bash)
  # - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
