language: php

php:
  - 7.1

matrix:
  include:
    - php: 7.1
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - bash <(curl -s https://codecov.io/bash) -t f97c6882-e454-4f0b-9d5b-5c5fd3bd0e30
  # - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
